---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
      description: The git repository URL
    - name: branch
      type: string
      description: The branch to build from
    - name: app-name
      type: string
      description: The name of the application
    - name: build-image
      type: string
      description: The build image
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: clone
      runAfter:
        - cleanup
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: output

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: output

    - name: test
      runAfter:
        - lint
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: build
      runAfter:
        - test
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
